"project_id": "720067"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "src/i18n"

"preserve_hierarchy": true

"files": [
  {
    "source": "en.json",
    "translation": "%two_letters_code%.json"
  }
]
