"project_id": "720067"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "/src/i18n/en.json",
    "translation": "/src/i18n/%two_letters_code%.json"
  }
]
